name = "fundador-uy"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fundador_db"
database_id = "a765c293-91bd-4980-97f2-0eddd3d99754" # Reemplazar con ID real
migrations_dir = "d1/migrations"
